version: '2'
services:
  couchdb:
    image: docker.io/couchdb:latest
    build: .
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'
    volumes:
      - couchdb:/bitnami/couchdb
volumes:
  couchdb_data:
   driver: local
